### PR TITLE
fix: use accurate from version in changeset and logging

### LINKED ISSUE #403: `prereleaseNPMTag` should be used instead of `latest` tag in prerelease mode
This is a follow-up issue after discussion in https://github.com/tophat/monodeploy/issues/292#issuecomment-879216394.

Currently in prerelese mode the `previousVersion` in changelog and changeset is using `latest` dist tag.

https://github.com/tophat/monodeploy/blob/5f775472f3014d3730cf326749a2d38ab50c1b1f/packages/node/src/index.ts#L228

Version from `latest` (`currentLatestVersion`) is also used in logging:

https://github.com/tophat/monodeploy/blob/d18c3374b1bd6f5cb0f81eea7c7dac1adc81ea50/packages/versions/src/applyReleases.ts#L97

Note you can't just change tag from "latest" to the `prereleaseNPMTag` dist tag though, because for a first prerelease, you do want to use "latest".

### PR DESCRIPTION
**Pull request by noahnu**
## Description

Expose previous and next versions in applyReleases so logging and changesets use an accurate "previous/from" version. The "previous" version should reflect the version that has the version strategy applied to it. This can be either current latest or current prerelease in prerelease mode (if the latest is newer than the pre-release).

## Related Issues

- Closes #403

### CODE REVIEW

File: packages/versions/src/applyReleases.ts [hunk 1]
```diff
@@ -80,39 +116,53 @@ const applyReleases = async ({
...
+            : { previous: null, next: null }
+
+        if (!next || !previous || previous === next) {
+            const version = config.prerelease
+                ? maxVersion(currentLatestVersion, currentPrereleaseVersion) ??
+                  currentLatestVersion
+                : currentLatestVersion
+            nonupdatedRegistryTags.set(packageName, {
+                previous: version,
+                next: version,
```
Comment (noahnu) [inline packages/versions/src/applyReleases.ts:136]: This is a bit of a change in behaviour. Previously non-updated packages were patched using the latest tag. Now they're patched using the prelease tag in prerelease mode (or latest if latest is newer than prerelease).
